float64 target_x # target position on canvas in meters
float64 target_y # target position on canvas in meters
float64 speed # speed in m/s, hack: negative speed will be interpreted as a stop motion in seconds
float64 penHeight # distance of the pen from the canvas in meters
float64 scale_done_dist # this should be by default 1., larger values (like 2.) make the drawing less precise but "faster" in execution
