# action applied to motion
int32 activateMotion   = 1
int32 deactivateMotion = 2
int32 action

# name of motion
string motionName
---
# indicates if the request was successful
bool success

# error messages with reason why it was not successful
string errorMessage
